name: "Sauce Labs Storage Action"
author: "Victor Hugo dos Santos (@vhsantos26)"
description: "Action responsible to upload the app into the Application Storage"
inputs:
  endpoint-action:
    description: 'Action to perform - options are "upload", "get-file-id", etc.'
    required: true
  sauce-labs-username:
    description: "Username credential"
    required: true
  sauce-labs-access-key:
    description: "Access key credential"
    required: true
  sauce-labs-data-center-host-name:
    description: "Data Center hostname"
    required: false
    default: https://api.us-west-1.saucelabs.com
  upload-file-path:
    description: "App file path (required for upload artifact)"
    required: false
  upload-artifact-description:
    description: "App build description (required for upload artifact)"
    required: false
    default: "Built from branch: ${{ (github.event_name == 'push' && github.ref) || (github.event_name == 'pull_request' && github.head_ref) }}. Workflow URL: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
  get-file-id-platform:
    description: "Platform to get the file from (required for get artifact)"
    required: false
    default: "ios"
  get-file-id-version:
    description: "Version to get the file from (required for get artifact)"
    required: false
    default: "1.0.0"
  git-file-id-build-number:
    description: "Build number to get the file from (required for get artifact)"
    required: false
    default: "1"
  get-file-id-description:
    description: "Description to get the file from (required for get artifact)"
    required: false
    default: "Built from branch: develop."
outputs:
  file-id: 
    description: 'File id generated by Sauce Labs'
branding:
  icon: upload-cloud
  color: red
runs:
  using: node16
  main: dist/index.js